### ISSUE TITLE
请问训练的数据样本可否提供，也可横向对比

### ISSUE THREAD

**Issue by cuicuizhang1989** [LCorleone/A-Simple-Chinese-License-Plate-Generator-and-Recognition-Framework#1]

**Comment by LCorleone** [comment]
https://github.com/szad670401/end-to-end-for-chinese-plate-recognition
这儿有制造训练数据的一些依赖文件，比如font，image等等，加入到路径中，配合我的代码你就能自己制造训练数据了。

**Comment by leoay** [comment]
人工合成的数据应用价值比较小

**Comment by LCorleone** [comment]
@LeoaY 是的，我也提到了人工合成的数据效果较差，这里只是提供了一个最简单的训练模型，如果使用实际车牌样本效果会好很多。
